version: '3.9'


services:

  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ./data/db:/data/db
  
  centilliondataback:
    image: centilliondataback_image:latest
    build:
      context: .
      dockerfile: Dockerfile
    # image: ${DOCKER_REGISTRY}/contact:${TAG}
    container_name: centilliondataback_container
    ports:
      - 80:80
    environment:
      MONGODB_URL: mongodb://db:27017
      # REDIS_URL: redis://redis:6379
    command: sh -c "uvicorn centilliondataback.app:app --host 0.0.0.0 --port 80 --reload"                  
    ##["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - db
   

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - 6379:6379


    